### ISSUE TITLE
No project LICENSE

### ISSUE THREAD

**Issue by alexandrevicenzi** [ProtonVPN/python-proton-vpn-network-manager-wireguard#1]
>  We are happy to answer your questions about the code or discuss technical ideas. 
 
Please complete the following checklist (by adding [x]):
- [x] I have searched open and closed issues for duplicates
- [x] This isn't a feature request
- [x] This is not a report about my app not working as expected

----------------------------------------

This repository has no LICENSE file, ideally, it should have one.

**Comment by calexandru2018** [comment]
@alexandrevicenzi thanks for raising this, but we've merged this and openvpn package into https://github.com/ProtonVPN/python-proton-vpn-network-manager, should be visible by next week.

**Comment by alexandrevicenzi** [comment]
@calexandru2018 good.

Packages being created, deprecated, and merged all the time causes a dependency nightmare for package managers. I hope the new VPN app reaches a stable API soon.

**Comment by calexandru2018** [comment]
We're fully aware of that, that's why we plan at doing the following in the upcoming weeks/months:
- Merge [python-proton-vpn-killswitch-network-manager-wireguard](https://github.com/ProtonVPN/python-proton-vpn-killswitch-network-manager-wireguard) into [python-proton-vpn-network-manager](https://github.com/ProtonVPN/python-proton-vpn-network-manager)
- Merge [python-proton-vpn-killswitch-network-manager](https://github.com/ProtonVPN/python-proton-vpn-killswitch-network-manager) into [python-proton-vpn-network-manager](https://github.com/ProtonVPN/python-proton-vpn-network-manager)
- Merge [python-proton-vpn-logger](https://github.com/ProtonVPN/python-proton-vpn-logger) into [python-proton-vpn-api-core](https://github.com/ProtonVPN/python-proton-vpn-api-core)
- Eventually merge also [python-proton-keyring-linux](https://github.com/ProtonVPN/python-proton-keyring-linux) into [python-proton-vpn-api-core](https://github.com/ProtonVPN/python-proton-vpn-api-core)

We're trying to reduce the packages as much as possible at this point, so it easier for maintainers to follow the updates, but also for us to work with anti-censorship measures.

**Comment by alexandrevicenzi** [comment]
I noticed that a few packages were already dropped, but new ones were added for WireGuard.

The updates are queued for openSUSE, in a few days we should have the WireGuard version available in official openSUSE repos, but newer packages require a bit more time and work from my side.

**Comment by calexandru2018** [comment]
Yeah for WG we have local agent (which is written in rust). Basically it's a tls-socket connection that communicates with our servers both ways, which improves the WG protocol. It will work without it (that why we still have the [fallback](https://github.com/ProtonVPN/python-proton-vpn-network-manager-wireguard/blob/master/proton/vpn/backend/linux/networkmanager/protocol/wireguard/local_agent/fallback_local_agent.py). Once we release the local-agent package it will eventually remove this.

**Comment by calexandru2018** [comment]
Hey @alexandrevicenzi , local-agent is out: https://github.com/ProtonVPN/python-proton-vpn-local-agent

- Wireguard and OpenVPN have been merged into: https://github.com/ProtonVPN/python-proton-vpn-network-manager
- Thus https://github.com/ProtonVPN/python-proton-vpn-network-manager-openvpn and https://github.com/ProtonVPN/python-proton-vpn-network-manager-wireguard are deprecated
